In [2]:
import numpy as np

In [3]:
array_1d=np.array([1,2,3,4,5])
array_1d

array([1, 2, 3, 4, 5])

In [5]:
type(array_1d) # show this is type of array or list

numpy.ndarray

In [7]:
array_1d.ndim   # ahow the whta type of dim of aaray

1

In [9]:
array_1d.shape  # show the shape of array in form of row and column

(5,)

In [11]:
array_1d.size # shoe the of array has total no. of element

5

In [ ]:
############### 2d array ################33

In [16]:
arr_2d=np.array([[1,2,3,4],[7,6,8,9,]])
arr_2d

array([[1, 2, 3, 4],
       [7, 6, 8, 9]])

In [17]:
type(arr_2d)

numpy.ndarray

In [18]:
arr_2d.ndim

2

In [19]:
arr_2d.shape

(2, 4)

In [20]:
arr_2d.size

8

In [22]:
arr_2d.dtype

dtype('int32')

In [23]:
##################same as 3d array###################3

In [24]:
arr_3d=np.array([[[1,2,3],[2,3,4],[4,6,7]]])
arr_3d

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 6, 7]]])