In [1]:
import numpy as np

In [3]:
arr_1s=np.array([[[1,1,1],[1,1,1],[1,1,1]]]) # its a lenghty process to print ones element matrix ML has by default one fn.
arr_1s

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [6]:
array1=np.ones(4)
array1

array([1., 1., 1., 1.])

In [7]:
array1.dtype # it provide float value by default

dtype('float64')

In [8]:
array1=np.ones((4,5))  #4 rows and 5 columns but it provide float value
array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
###change float value to int value 

In [9]:
array1=np.ones((4,5),dtype=int)
array1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
array1=np.ones((4,5),dtype=bool) # print bool value 
array1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
#############create zeros matrix

In [12]:
array=np.zeros((3,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
array=np.zeros((3,4),dtype=bool)
array

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])