In [1]:
import numpy as np

# arange fn.

In [2]:
A=np.arange(1,13) #np.arange(start,ends,step)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
even_array=np.arange(2,13,2)
even_array

array([ 2,  4,  6,  8, 10, 12])

# linspace fn.

In [4]:
array=np.linspace(1,7,5)
array

array([1. , 2.5, 4. , 5.5, 7. ])

# Reshape fn. 

In [5]:
array1d=np.arange(1,13)
array1d                           # this is 1d array now we change it into 2d array using reshape fn.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
array2d=array1d.reshape(3,4)  # change into 3 rows and 4 column forms
array2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
array2d=array1d.reshape(3,4)  # change into 3 rows and 4 column forms
array2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
array2d=array1d.reshape(2,6)  # change into 2 rows and 6 column forms
array2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# convert 1d to 3d array

In [10]:
array3d=array1d.reshape((2,3,2))
array3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [11]:
#create 2d matrix using array and reshape fn .create in one line

In [13]:
array2=np.arange(1,13).reshape(2,6)
array2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# ravel fn. 

In [ ]:
# ravel fn. is used to convert multidimensional array to 1d array

In [14]:
# first print multidim array

In [15]:
array2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
array2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
# print convrt 3d to 1d

In [18]:
array3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [19]:
array3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten fn.

In [21]:
# it is work same as ravel fn.

array3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose

In [22]:
#convert row into columns

In [23]:
array3d.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [24]:
# or

In [25]:
array3d.T

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

AttributeError: module 'numpy' has no attribute 'array1d'