In [1]:
import numpy as np

In [2]:
#crete two matrix in one line

In [8]:
array1=np.arange(1,10).reshape(3,3)
array2=np.arange(1,10).reshape(3,3)

In [6]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#addition of array1 and array2

In [11]:
array1+array2  # or we can add with add() fn.

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
np.add(array1,array2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#same as subtraction of array

In [13]:
array1-array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.subtract(array1,array2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
# devide

In [16]:
array1/array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.divide(array1,array2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# mlutiply

In [20]:
array1*array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
np.multiply(array1,array2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
# now multiply row to column

In [23]:
array1@array2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [24]:
# or

In [25]:
array1.dot(array2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# find max value of array

In [26]:
array1.max()

9

In [28]:
# find index of max value
array1.argmax()

8

In [ ]:
# means array jo max value 9 h uska index no. 8 h

In [32]:
# find max value of each row and column by axis fn. 1--> represent for row and 0---> represent for column

In [33]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array1.max(axis=0)

array([7, 8, 9])

In [31]:
array1.max(axis=1)

array([3, 6, 9])

In [34]:
# same as min fn.

In [35]:
array1.min()

1

In [36]:
array1.argmin()

0

In [37]:
array1.min(axis=0)

array([1, 2, 3])

In [38]:
array1.min(1)

array([1, 4, 7])

In [ ]:
# total sum of matric 

In [39]:
array1.sum()  # sum of all element of array1

45

In [40]:
# suppose we want to sum of all columns of array1

In [41]:
np.sum(array1,axis=0)

array([12, 15, 18])

In [42]:
# now sum of all row

In [43]:
np.sum(array1,axis=1)

array([ 6, 15, 24])

In [44]:
# average of array1

In [45]:
np.mean(array1)

5.0

In [46]:
# sqrt root of all elemnt of array1

In [47]:
np.sqrt(array1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [48]:
# standard division

In [49]:
np.std(array1)

2.581988897471611

In [50]:
# exponenet of all elemnt of array1

In [51]:
np.exp(array1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [52]:
#natural log fn.

In [53]:
np.log(array1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [54]:
# log base 10

In [55]:
np.log10(array1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])