In [1]:
import numpy as np

In [3]:
array=np.arange(1,101).reshape(10,10)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
# now access the elemet by index

In [4]:
array[0,0]

1

In [5]:
# check the dim of elemnt

In [6]:
array[0,0].ndim

0

In [7]:
# it has no dim then it is scalar value

In [8]:
# now access row and column

In [9]:
array[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
array[0].ndim  # accees the row

1

In [ ]:
# it is 1d array

In [12]:
array[ :,0]   # access the column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [13]:
array[ :,0].ndim  # check dim

1

In [14]:
#now we access the column but accees in 2d 

In [15]:
array[ :,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [16]:
array[ :,0:1].ndim # check dim

2

In [17]:
# column is access in 2d array

In [18]:
# now access row and column randomly

In [19]:
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [20]:
array[2:5,1:4]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [21]:
array[ :,1:3] #access all row and 2nd 3rd column

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [22]:
array[1:3,] # access 2nd and 3rd row and all column

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])