In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv("D:\\datasets\\1000_Companies.csv")
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
real_x=data.iloc[:,0:4].values
real_x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       ...,
       [100275.47, 241926.31, 227142.82, 'California'],
       [128456.23, 321652.14, 281692.32, 'California'],
       [161181.72, 270939.86, 295442.17, 'New York']], dtype=object)

In [4]:
real_y=data.iloc[ :,4]
real_y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [5]:
from sklearn.preprocessing import LabelEncoder

# labelEncoder split into different dummy variables

LE=LabelEncoder()
real_x[:,3]=LE.fit_transform(real_x[:,3]) # 3rd column ko encode karega or usi me save kar dega
real_x[:,3]

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2,
       0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0,
       2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0,
       1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2,
       0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2,
       1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0,
       1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0,
       2, 0, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0,
       2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0,
       2, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1,
       2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 1,

In [6]:
# but we want binary form data so import another library oneHotEcoder

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
OHencoder=OneHotEncoder(categorical_features=[3])  # we have three categorial data in cities so gives 3

real_x=OHencoder.fit_transform(real_x).toarray()
real_x


C:\Users\vijay\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\vijay\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0027547e+05,
        2.4192631e+05, 2.2714282e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.2845623e+05,
        3.2165214e+05, 2.8169232e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6118172e+05,
        2.7093986e+05, 2.9544217e+05]])

In [7]:
# avoiding dummy variable trap
real_x=real_x[:,1:]
real_x

array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 1.0027547e+05, 2.4192631e+05,
        2.2714282e+05],
       [0.0000000e+00, 0.0000000e+00, 1.2845623e+05, 3.2165214e+05,
        2.8169232e+05],
       [0.0000000e+00, 1.0000000e+00, 1.6118172e+05, 2.7093986e+05,
        2.9544217e+05]])

In [8]:
# now training or testing data ko split krenge

train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=0.2,random_state=0) 
#now build the linear model

MLR=LinearRegression()
MLR.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
# predicting the test set results
pred_y=MLR.predict(test_x)
pred_y

array([ 89790.61532916,  88427.07187362,  94894.67836972, 175680.86725609,
        83411.73042089, 110571.90200074, 132145.22936441,  91473.37719687,
       164597.05380605,  53222.82667402,  66950.19050991, 150566.43987004,
       126915.20858596,  59337.85971051, 177513.9105306 ,  75316.28143052,
       118248.14406603, 164574.40699901, 170937.28981069, 182069.11645083,
       118845.03252689,  85669.95112229, 180992.59396142,  84145.08220146,
       105005.83769214, 101233.56772747,  53831.07669092,  56881.41475226,
        68896.39346906, 210040.00765882, 120778.72270894, 111724.87157655,
       101487.90541518, 137959.02649623,  63969.95996744, 108857.91214127,
       186014.72531986, 171442.64130746, 174644.26529203, 117671.49128195,
        96731.37857434, 165452.25779408, 107724.34331255,  50194.54176915,
       116513.89532179,  58632.48986822, 158416.46827609,  78541.4852161 ,
       159727.66671742, 131137.87699644, 184880.70924515, 174609.08266879,
        93745.66352059,  

In [10]:
#calculating the coeficient 
MLR.coef_

array([-8.80536598e+02, -6.98169073e+02,  5.25845857e-01,  8.44390881e-01,
        1.07574255e-01])

In [11]:
MLR.intercept_


-51035.229724023025

In [12]:
from sklearn.metrics import r2_score
r2_score(test_y,pred_y)

0.9112695892268757